replace bar_chart with svg instead of using matplotlib
greenbone/pheme pull request #123
Opened 2020-11-27 16:18 UTC by nichtsfrei

To have more fine granular control over the bar chart and get an easier
transfer between designer and pheme integration the matplotlib bar chart
gets replaced with an svg template.

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/pheme/blob/master/CHANGELOG.md) Entry
- [ ] Documentation

2020-11-30 08:34 UTC, y0urself requested changes

2020-11-30 08:34 UTC, y0urself commented on pheme/templatetags/charts.py
> +__BAR_ELEMENTS_TEMPLATE = """
```suggestion
__BAR_ELEMENT_TEMPLATE = """
```

2020-11-30 08:34 UTC, y0urself commented on pheme/templatetags/charts.py
> +            elements += __BAR_ELEMENTS_TEMPLATE.format(element_x, width, color)
```suggestion
            elements += __BAR_ELEMENT_TEMPLATE.format(element_x, width, color)
```

2020-11-30 08:34 UTC, y0urself commented on pheme/templatetags/charts.py
> +<!-- transform everytime +44 of previous -->
```suggestion
<!-- transform y everytime +44 of previous -->
```

2020-11-30 08:34 UTC, y0urself commented on pheme/templatetags/charts.py
> +        height=len(chart_data.keys()) * bar_jump, bars=bars, legend=""
`legend` Just a placeholder for later?

2020-11-30 09:39 UTC, nichtsfrei commented on pheme/templatetags/charts.py
> +        height=len(chart_data.keys()) * bar_jump, bars=bars, legend=""
it's a draft, but, yes :)

2020-11-30 19:17 UTC, y0urself commented on pheme/templatetags/charts.py
> +        )
```suggestion
        for i in range(int(max_sum / orientation_basis + 1)):
            orientation_lines, orientation_labels = __add_orientation(
                i, orientation_lines, orientation_labels
            )
```

2020-12-01 07:26 UTC, y0urself approved these changes

2020-12-01 07:26 UTC, merged