Init pheme container
greenbone/pheme pull request #380
Opened 2021-11-08 14:21 UTC by y0urself

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/pheme/blob/main/CHANGELOG.md) Entry
- [ ] Documentation

2021-11-17 07:48 UTC, y0urself commented on .github/workflows/container.yml
> +          file: .docker/pheme.Dockerfile
```suggestion
          file: .docker/pheme.Dockerfile

```

2021-11-17 08:10 UTC, bjoernricks requested changes

2021-11-17 08:10 UTC, bjoernricks commented on .docker/pheme.Dockerfile
> +    python3-rpm && \
```suggestion
```

2021-11-17 08:10 UTC, bjoernricks commented on .github/workflows/container.yml
> +    branches: [ main ]
```suggestion
```

2021-11-17 08:10 UTC, bjoernricks commented on .github/workflows/container.yml
> +        uses: greenbone/actions/reference-version@v1
```suggestion
      - name: Gather container tags
        id: container
        uses: greenbone/actions/container-image-tags@v1
```

2021-11-17 08:10 UTC, bjoernricks commented on .github/workflows/container.yml
> +          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.VERSION }}
```suggestion
          tags: ${{ steps.container.outputs.image-tags }}
```

2021-11-29 10:11 UTC, bjoernricks approved these changes

2021-12-06 07:21 UTC, merged